### ISSUE TITLE
Active deepsource for fireant

### ISSUE THREAD

**Issue by lewismc** [fireant-ci/fireant#2]
[Deepsource](https://deepsource.io/) allows us to automate code reviews with static analysis. I want someone to take the lead on activating Deepsource so we can Identy and fix bug risks, anti-patterns, performance issues, and security flaws on every commit and pull request.

**Comment by jamie-meyer** [comment]
Deepsource is now active on the main branch

**Comment by lewismc** [comment]
Again @jamie-meyer thank you for taking this one on. For guidance on augmenting the .deepsource.toml please see https://github.com/capstone-coal/pycoal/blob/master/.deepsource.toml
Also, please create a pull request in the future so we can trace the fix to the original issue. Thank you
