### ISSUE TITLE
Activate requires.io

### ISSUE THREAD

**Issue by lewismc** [fireant-ci/fireant#3]
[requires.io](https://requires.io/) ensures that all dependencies we use stay secure and up-to-date. Please activate it for Fireant.

**Comment by jamie-meyer** [comment]
requires.io is now activated -- seems like it's not working though. It's stuck on a waiting screen trying to load the requirements. I will update this issue if it changes as I only activated it minutes ago.

**Comment by lewismc** [comment]
@jamie-meyer where is the requires.io page for the project?
Please add a badge to the README similar to the one which can be found on the [README for pycoal](https://github.com/capstone-coal/pycoal/blob/master/README.rst)

**Comment by lewismc** [comment]
Also, I didn't see a pull request for this one. In the future please assign yourself to the issue and provide a pull request. Thank you very much @jamie-meyer for taking this one on.
